title: "Base Apparel coming soon page"
description: "Frontend Mentor Challenge"
baseurl: "" # if deploying to a sub-path, add it here
url: "https://zoetlam.github.io" # or the appropriate URL for GitHub Pages
